### PR TITLE
Fixed a few typos in documentation files [issue 118]

### PR DESCRIPTION
**Pull request by krook**
As noted in issue #118, this is a resubmitted pull request targeted at the develop branch that contains the typo fixes suggested in PR #110 (which was incorrectly targeted at the master branch).

I addressed a few minor typos, and made usage of the word "buildpack" and "Cloud Foundry" with a space consistent throughout the documentation. 

I also added a few references to IBM Bluemix and generic CF instances where appropriate along with mention of Pivotal Web Services.

### CODE REVIEW

**Comment by flavorjones** [comment]
I'll read through the proposed changes as soon as I can! Tagging @Dannyzen in case he wants to review.

**Comment by krook** [comment]
Thanks @flavorjones and @Dannyzen

**Comment by Dannyzen** [comment]
@krook Thanks for proposing these changes. Most of these changes look great! I'm questioning the mention of any vendor or products at all. What do you think about removing all IBM & Pivotal references?

**Comment by krook** [comment]
@Dannyzen That's a good question. I'm fine removing vendor references in most of the supporting docs, but I think it may have some value to mention where this buildpack can run, beyond a user's own CF instance. Maybe we just add a link to https://www.cloudfoundry.org/learn/providers/ ?

**Comment by krook** [comment]
@Dannyzen And by that, I mean just adding the link to the very first section of the README.md, and removing vendor references elsewhere.

**Comment by dmikusa-pivotal** [comment]
+1 no vendor references.  The build pack is vendor agnostic, so I'm not sure why the docs for it should have references in it.  If there are references to PWS, it's a legacy thing, because that's were I did all the early development.  At this point, I'd say any references like that should be removed or replaced with just Cloud Foundry.

Only exception that comes to mind is the "Getting Help" section.  Reason being, to prevent users from sending vendor specific questions to the cf-dev mailing list.  Maybe this section could link to the providers page @krook mentioned, and say "check with your provider for support or if you're running your own the cf-dev mailing list" or something like that.

**Comment by krook** [comment]
I agree with @dmikusa-pivotal on limiting the vendor mentions to the Getting Help section of the README.md. If you all agree, can we merge this current PR, then I'll open up a separate Issue/PR to address that specifically?

**Comment by Dannyzen** [comment]
I too agree with @dmikusa-pivotal. @Krook in the interest of keeping things tidy, would you mind adjusting this pull request with a new commit that removes any mentions of vendors and includes the changes to the "Getting Help" section? That should wrap this pull request up and put us where we want to be.

**Comment by krook** [comment]
@Dannyzen Will do!

**Comment by krook** [comment]
@Dannyzen @dmikusa-pivotal @flavorjones I've pulled the latest from the `develop` branch, then added a new commit with the changes to README.md and docs/binaries.md to remove the vendor specific references.

**Comment by Dannyzen** [comment]
Thanks for the update @krook. What are your thoughts on an additional modification which includes a link to https://www.cloudfoundry.org/learn/providers/ in the "Getting Help" section and removing any vendor mentions?

**Comment by krook** [comment]
@Dannyzen I did include that change in the latest README.md commit: https://github.com/krook/php-buildpack/commit/f306f5e1208c30ae60bcb14f286a08cff2f16792#diff-04c6e90faac2675aa89e2176d2eec7d8L93

**Comment by krook** [comment]
Hi @Dannyzen @flavorjones - Any other changes needed for this PR?

**Comment by Dannyzen** [comment]
Thanks for the help @krook I've merged these changes in.

**Pull request merged**
