### PR TITLE
CA APM PHP Agent support

### PR DESCRIPTION
**Pull request by sasanka-pusapati**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
  
CA APM PHP Agent support

* An explanation of the use cases your change solves

Helps the buildpack user to monitor the PHP applications using CA APM PHP agent.

* [ x ] I have viewed signed and have submitted the Contributor License Agreement

* [ x ] I have made this pull request to the `develop` branch

* [ x ] I have added an integration test

### CODE REVIEW

**Comment by sclevine** [comment]
Let us know when this is ready for review.

**Comment by sasanka-pusapati** [comment]
@sclevine 
Changes are ready for review.

**Comment by sasanka-pusapati** [comment]
Hi @sclevine 

Is it possible to provide an approximate timeline for completion of this review from your side , for us to track the release internally.

Thanks,
Sasanka.

**Comment by sclevine** [comment]
Apologies for the delay. The review is scheduled for late this week or early next week. Assuming everything looks good, we should be able to merge this for the next release. You can follow the associated story in tracker for updates.

**Comment by dgodd** [comment]
See https://github.com/cloudfoundry/php-buildpack/pull/220#issuecomment-319685754 for CLA

**Comment by dgodd** [comment]
@sasanka-pusapati I am about to merge this. However could I ask for a way to have some form of account so that we can start doing some form of full integration test ; eg. Check an API to confirm that data has in fact been received by appdynamics. We would like to have more certainty that everything works for customers

**Pull request merged**
