### PR TITLE
Modsecurity integration & configuration

### PR DESCRIPTION
**Pull request by bonfilsd**
_Proposed change:_

Adds support for Web Application Firewall following discussion in https://github.com/cloudfoundry/php-buildpack/issues/221#issuecomment-331185109 Sorry @sclevine for late follow up on this issue.

_Use cases your change solves:_

Provides WAF features in php buildpack natively. Orange used to maintain a php buildpack fork to get this feature.

* [x] I have made this pull request to the `develop` branch
* [ ] I have added an integration test. Guidance would be highly appreciated.

--------------------------

### php-buildpack repository

_Detailed decription:_
- only apache httpd is supported 
- modsecurity core version is 2.9.2
- modsecurity Core Rule Set (CRS) version is 3.0.2

Also, by default, modsecurity module is not enabled.

```apache
#LoadModule security2_module modules/mod_security2.so
```

When enabling `mod_security` module, users also need to activate the `unique_id` module required as a dependency.

```apache
#LoadModule unique_id_module modules/mod_unique_id.so
```

In addition, for configuration file needs, 5 environments variables & directories have been created

* environment variables:
  * MODSECURITY_AUDIT_DIR
  * MODSECURITY_CRS_DIR
  * MODSECURITY_LOG_DIR
  * MODSECURITY_TMP_DIR
  * MODSECURITY_UPLOAD_DIR

* directories:
  * app/modsecurity/audit
  * app/modsecurity/crs # for rules and configuration files
  * app/modsecurity/log
  * app/modsecurity/tmp
  * app/modsecurity/upload

### binary-builder repository
Obviously, new recipe for httpd is needed to the manifest.yml file.

This recipe is available in the following modsecurity branch (pending related PR)
* https://github.com/orange-cloudfoundry/binary-builder/tree/modsecurity

and comparison here : 
* https://github.com/orange-cloudfoundry/binary-builder/compare/master...orange-cloudfoundry:modsecurity

### docs-buildpacks repository
In addition, documentation has been done to explain how to activate & configure modsecurity for PHP buildpack.

This documentation is available in the following modsecurity branch (pending related PR)
* https://github.com/bonfilsd/docs-buildpacks/tree/modsecurity

and PR here
* https://github.com/orange-cloudfoundry/docs-buildpacks/pull/1

and comparison here :
* https://github.com/orange-cloudfoundry/docs-buildpacks/compare/modsecurity...bonfilsd:modsecurity

Thanks in advance for your feedback 

/CC @gberche-orange & @ArthurHlt 

--

### CODE REVIEW

**Comment by sclevine** [comment]
@dmikusa-pivotal thoughts on this?

**Comment by dmikusa-pivotal** [comment]
I took a quick look.  My main concern is this.  There's an awful lot of mod_security config being pulled into the buildpack.  If this changes even somewhat infrequently, that's going to be an issue as we're going to need to make sure the buildpack is being updated.

My $0.02 is that the mod_security and mod_security core rule set should be unique versioned dependencies provided by binary-builder.  We already have the infrastructure there to monitor for updates and turn out new buildpacks that will make those versions available.

Outside of that, I think it would be nice to have an easier way to enable the configuration.  Rather than needing to override the modules config file.  Either an option in options.json or an environment variable would be my thought.  That would just auto enable the two modules.

**Comment by bonfilsd** [comment]
Read "Forgot" and not "Forget" for commit message

**Comment by sclevine** [comment]
Sorry for the delay!

We are considering making some major changes to this buildpack after merging #260. We'd like to hold off on merging this for now. If we request more changes, they would likely need to be re-written in the future anyways.

**Comment by Zanadar** [comment]
Closing as stale. @dmikusa-pivotal feel free to re-open if you see fit.

**Pull request closed without merging**
