### PR TITLE
AppDynamics Monitoring Extension support

### PR DESCRIPTION
**Pull request by thesrinivas**
Updated based on initial comments

### CODE REVIEW

**Comment by pranta** [comment]
@flavorjones already the CLA for AppDynamics - please check with him.

**Comment by jtarchie** [comment]
Hi @pranta,

Thanks for the pull request.

* We won't accept the pull request with so many commits, they should be squashed down to a single commit to keep the projects `git` history clean.

* We like to test out our PRs to make sure the expected functionality works with our test suites and apps. There is [documentation](https://docs.cloudfoundry.org/buildpacks/php/gsg-php-newrelic.html) that describes how to setup New Relic. Could you please provide similar documentation on how to use the extension?

* I noticed that you deleted the test file in the last commit 8b42b5f. Could you please provide test coverage for the expected user flow? We like to have tests for future development, just in case regressions are introduced. We have more information about the [unit tests](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/development.md#testing), but if you have any questions feel free to ask us.

@jtarchie

**Comment by jtarchie** [comment]
@thesrinivas, it looks like your commits were rebased and you modified previous commits.

For example, this [commit](https://github.com/thesrinivas/php-buildpack/commit/a8c9d74e47cec26c51d89876e21a56a6f28b3b21) reset the author to me and you. This caused the commits to be allocated new SHAs, therefore, the history was rewritten.

This might have happened because you did a rebase against our remote (cloudfoundry/php-buildpack) rather than your remote (thesrinivas/php-buildpack).

**Comment by nkatre** [comment]
Can you delete this pull request as the person who submitted this PR is no longer with AppDynamics

**Comment by Dannyzen** [comment]
Note: This PR has been closed as per the request of AppDynamics

**Pull request closed without merging**
