### PR TITLE
Update options.json

### PR DESCRIPTION
**Pull request by anirudha123**

### CODE REVIEW

**Comment by jtarchie** [comment]
@anirudha123, thanks for the pull request. Can you provide feedback why you'd like us to pull this in?

**Comment by anirudha123** [comment]
hi

my PHP installation appears to be missing the MySQL extension which is
required by WordPresswhen I am hosting wordpress in ibm bluemix cloud.
thats why i want to change the file.


Regards
Anirudha Rath
Ph no-+919040331611
SDRC Pvt. Ltd.
Enabling social change initiatives.

**Comment by dmikusa-pivotal** [comment]
The PHP build pack does not enable these extensions by default.  This is intentional.  Every extension that's enabled increases the memory requirements of PHP (some a little, some a lot).  Since not everyone's application will need them, the build pack only enables a very small set of basic extensions out-of-the-box.

As Mike & JT mentioned, the build pack also makes it *very* easy for you to turn on the extensions that are needed by *your* application, so there's no reason to change the defaults.

**Comment by flavorjones** [comment]
Hi @anirudha123,

JT linked to the documentation which explains how you can make this change in your application folder, and not in the base buildpack.

To summarize, though, here's what you do:

* create a subdirectory in your application folder named `.bp-config`
* create a file named `options.json` in that subdirectory
* the contents of `options.json` should be:

```js
{
    "PHP_EXTENSIONS": ["bz2", "zlib", "curl", "mcrypt", "mysqli", "gd", "zip"]
}
```

or an alternative set of modules.

In this way, you can customize the buildpack behavior for each app. I hope this makes sense?

Thanks for using Cloud Foundry.

**Comment by anirudha123** [comment]
Thank you for the post. I have changed  php extension in option.json file
which is present in php-buildpack. Then deployed it in ibm bluemix for
wordpress site. Now the wordpress site working fine with php extension for
mysql enabled.

Thank you again for the post.  Wish you happy diwali.

**Pull request closed without merging**
