### PR TITLE
Fix typos in php.ini files

### PR DESCRIPTION
**Pull request by karasaj**

### CODE REVIEW

**Comment by mmb** [comment]
Closing and re-opening in order to trigger CLA request (cfdreddbot).

**Comment by mmb** [comment]
re-opening.

**Comment by mmb** [comment]
Closing and re-opening in order to trigger CLA request (cfdreddbot).

**Comment by jchesterpivotal** [comment]
Hi @karasaj, can you sign the CLA? We're happy to pull this one in once the lawyers are squared away.

**Comment by karasaj** [comment]
Is it enough to fill it out electronically and attach here?

**Comment by jchesterpivotal** [comment]
I'm not sure. @jbayer @MarkKropf ?

**Comment by jbayer** [comment]
@karasaj as described in CLAs available with links here [1] please send them to contributors@cloudfoundry.org and electronically is fine.

[1] https://github.com/cloudfoundry/cf-release/blob/master/CONTRIBUTING.md#contributor-license-agreement

**Comment by jchesterpivotal** [comment]
@karasaj Can you advise whether you've submitted a CLA? We're keen to pull this in.

**Comment by karasaj** [comment]
Very sorry! I had a lot on ny plate this last week and it slipped my mind. I'll have it submitted by the end of today.  

Sent from Outlook

    _____________________________

**Comment by karasaj** [comment]
Hi again,
I've submitted the CLA. Let me know if there's any trouble.
Date: Wed, 4 Feb 2015 21:09:11 +0000

**Comment by jbayer** [comment]
we received the signed CLA, please proceed @MarkKropf @jchesterpivotal

**Pull request merged**
