### PR TITLE
Fixed debug console script URL

### PR DESCRIPTION
**Pull request by RickvdP**
The debug.sh script and the repo it is in apparently got renamed, small fix.

### CODE REVIEW

**Comment by RickvdP** [comment]
Filled in and sent the individual CLA, maybe not that useful for this small contribution but I'm going to guess this won't be my last PR.

**Comment by flavorjones** [comment]
Hey, @RickvdP!

Thanks for this contribution! I have to just double-check that the Foundation has your CLA, and then we'll go ahead and merge this.

Thanks for your patience!

**Comment by jtarchie** [comment]
@cfdreddbot reload!

**Comment by jtarchie** [comment]
@cfdreddbot reload!

**Pull request merged**
