### PR TITLE
Bump version to 4.6.0

### PR DESCRIPTION
**Pull request by sophiewigmore**
Finishes work to support `cflinuxfs4`

### CODE REVIEW

**Comment by sophiewigmore** [comment]
Do not merge until CI tests are green

**Comment by sophiewigmore** [comment]
@arjun024 @brayanhenao should a cflinuxfs4 support release be a minor release? or a major?

**Comment by brayanhenao** [comment]
@sophiewigmore A minor version is required ([ref](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Add-cflinuxfs4-support-for-a-Buildpack#release-a-new-version-of-the-buildpack)). So it would be 4.6.0

**Comment by brayanhenao** [comment]
@sophiewigmore the `VERSION` file should not have a new line at the end. Use the `echo -n` trick

**Pull request merged**
