### PR TITLE
IBM DB Integration

### PR DESCRIPTION
**Pull request by fishfin**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* IBM DB Extensions are integrated.

* This will allow PHP applications to connect to IBM databases out of the box (DB2, dashDB).

* [Yes] I have viewed signed and have submitted the Contributor License Agreement

* [Yes] I have made this pull request to the `develop` branch

* [No] I have added an integration test

### CODE REVIEW

**Comment by sesmith177** [comment]
@fishfin Thank you for the interest. For these buildpacks we have a few constraints which we need to work out solutions for with you.

1. Many of the users of these buildpacks need to be able to run them when disconnected from the public internet. For this reason we need a way to make features like this have a way to embed all of their resources into the buildpack (we can discuss our methods more if you are interested)

2. We would need to obtain trusted binaries. The users of this buildpack trust that we have vetted the binaries (or compiled from source in a transparent fashion), thus we can't download them from a private github repository.

To move forward we would need to work through the above with you.

We have also been discussing adding the ability for an application to use extra PHP Extensions (PECL) without altering the buildpack. Would this be of interest to you?

**Comment by fishfin** [comment]
Hello Sam,

Thank you much for your review.

1) Yes, I am interested in understanding how I could embed the external
resources (ibm_db2 extension and DB2 drivers) into the buildpack directly.
I tried searching, maybe didn't give the right keywords, then I took help
of the CloudFoundry base buildpack and Heroku buildpack as my reference and
coded the current buildpack.

2) Two things on the binaries:
- I have compiled ibm_db2 from https://pecl.php.net/package/ibm_db2 for
each of three PHP major versions (5.5, 5.6, 7.0). Could you please let me
know a way where I can make this compilation process transparent to the
users?
- I have repackaged CLI Driver binaries (because of size limitations on
GitHub) into two separate packages. These are IBM provided binaries as-is.
Could you please suggest me a better way? I could try directly linking it a
direct download page (I am not sure if there is one, because the one I know
requires me to download it after logging in with my ID after a free
registration with the IBM site, but will try to find one). Assuming that I
find a way to directly download the CLI Drivers, I can see there would
still be two challenges:
    a) It is still an online process and wouldn't work for users not
connected to public internet.
    b) I will only have the binaries, not the source code.

Kind Regards,
fishfin

**Comment by dmikusa-pivotal** [comment]
You might want to look at [binary-builder](https://github.com/cloudfoundry/binary-builder).  We added [support for Oracle](https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php_common.rb#L155-L220) and [this](https://github.com/cloudfoundry/binary-builder/blob/master/PHP-Oracle.md).  I suspect that adding support for IBM DB would be similar.

**Comment by fishfin** [comment]
Thanks for your note, I will look into these. I am not aware of some of the
things listed there, so it might take me some time to get it working that
way. You can put this Pull Request on hold or cancel it, and I will put it
again when I am ready.

**Comment by sclevine** [comment]
Also worth noting: if the DB2 drivers included in the buildpack aren't OSS, we may have trouble accepting the PR

**Comment by fishfin** [comment]
Sorry, but could you please tell me what "OSS" stands for?

**Comment by dmikusa-pivotal** [comment]
OSS == Open Source Software

**Pull request closed without merging**
