### PR TITLE
Fix relative link to composer.md

### PR DESCRIPTION
**Pull request by NoelLH**
Documentation: Fix relative link to composer.md

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
Hi @NoelLH, thanks for the pull request! Would you mind rebasing this off develop and fixing the merge conflicts? Thanks.

**Comment by NoelLH** [comment]
Hi @RochesterinNYC - I'd like to, but on further inspection it looks like the file that link went to - plus `config.md` itself and a bunch of others - are all removed on `develop`.

The [commit says](https://github.com/cloudfoundry/php-buildpack/commit/dd330ca9286599eccc51c1e52a70209df1fe8782) _"Migrated the PHP Docs from /docs to the CF docs site"_ but I can't see a comparable replacement for e.g. the Composer info. Am I missing something?

**Comment by RochesterinNYC** [comment]
@NoelLH, ah thanks for pointing that out. We've actually recently moved the docs over to the official Cloud Foundry docs to ensure centralization and that there is one source of truth. We have a section/page dedicated to Composer: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-composer.html

If you want to make pull requests improving or correcting that documentation, it's available in https://github.com/cloudfoundry/docs-buildpacks

**Comment by NoelLH** [comment]
Makes sense, thanks!

**Pull request closed without merging**
