### PR TITLE
removed get-param and added header

### PR DESCRIPTION
**Pull request by thschue**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
removed the api-token parameter from the url and added it as a header in the request

* An explanation of the use cases your change solves

* [ X ] I have viewed signed and have submitted the Contributor License Agreement

* [ X ] I have made this pull request to the `develop` branch

* [ ] I have added an integration test

### CODE REVIEW

**Comment by dwillist** [comment]
Looks good, if you could sign the CLA think we can merge this.

**Comment by dfreilich** [comment]
Hey @thomschuetz! As Dan mentioned, if you could sign the CLA, we can look into merging it.

**Comment by thomschuetz** [comment]
> Hey @thomschuetz! As Dan mentioned, if you could sign the CLA, we can look into merging it.

Hello @dfreilich! The CLA is signed, so could you merge it?

**Comment by DTMad** [comment]
Hey! CLA is signed - hurray! Any update when this will be merged?

**Comment by arthfl** [comment]
Any ETA on this?
Since the CLA is signed for a while now :-)

**Pull request merged**
