### PR TITLE
Convert to libbuildpack

### PR DESCRIPTION
**Pull request by dgodd**
- Used buildpack-packager skeleton as starting point
- Install httpd and php
- converted templates to go templates
- moved $HOME/php and $HOME/nginx to deps dir
    
CHANGED: (See: SkipIntentionallyRemovedFunctionality)
- removed nginx from manifest.yml
- bin/detect is MUCH simpler. Just looks for **/*.php
   (this may not be good enough???)
- moving files from root to default webdir if it doesn't exist
    
NOT YET DONE: (See: SkipNotYetImplementedFunctionality)
- all extensions. (eg newrelic, geoip)

### CODE REVIEW

**Comment by sclevine** [comment]
🎉 🎆 😄

**Comment by sclevine** [comment]
@dmikusa-pivotal

**Comment by dmikusa-pivotal** [comment]
This is awesome.  I hope to play with it more, but here's two quick comments:

>bin/detect is MUCH simpler. Just looks for **/*.php
>(this may not be good enough???)

Currently, I believe we're looking for three things (in this order):

1.) composer.json
2.) any PHP files (i.e. ends with `*.php`)
3.) the WEBDIR (i.e. `htdocs` or `public`, whatever was configured)

Just looking for PHP files might work.  I'm trying to think of cases where there could be a composer.json file or a WEBDIR but have no PHP files.  Nothing is coming to mind.

>moving files from root to default webdir if it doesn't exist

I strongly believe we should take this opportunity to *not* move files around.  Whatever get's uploaded should be what the user gets.  I think this has been a source of confusion for users.  More confusion than benefit.

**Comment by Zanadar** [comment]
Closing as stale.

**Comment by Zanadar** [comment]
@sclevine Any clue what happened here? Is this dead?

**Pull request closed without merging**
