### PR TITLE
AppDynamics PHP agent

### PR DESCRIPTION
**Pull request by nkatre**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
  Download and install appdynamics php agent

* An explanation of the use cases your change solves
  Monitor php applications using appdynamics

* [ x] I have viewed signed and have submitted the Contributor License Agreement

* [x ] I have made this pull request to the `develop` branch

* [ x] I have added an integration test

### CODE REVIEW

**Comment by sclevine** [comment]
Thanks @nkatre, looks good! We won't be able to merge this until after June 1st, due to the export control restrictions on the agent. See [here](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/SN5AW5SUAMHDQAAPU45AURTBWEXWU2MN/) for more details. We will handle any merge conflicts that result from the delay.

**Comment by dgodd** [comment]
Looking at merging and noticed that you both build a dynamic URL to download and include the same URL in the manifest.yml. Do you need the dynamic nature? We should change it to either using the URL in the manifest.yml or removing it.

Do you really intend to install the agent at startup rather than during staging? If possible I feel it would be better for users if the install happened at staging.

**Comment by nkatre** [comment]
Yes, we do need the dynamic nature of the URL, the version numbers when changed, changes the URL for downloading that specific binary version. Yes, I have tried multiple ways of installing the agent however this seems reasonable for our use-case.

**Comment by athornton2012** [comment]
@nkatre it actually looks like you are installing the agent during staging rather than launch. But your function `_service_environment` (which is supposed to set environment variables in the application container that the app will run in), is only setting environment variables in the staging container. In order to set appropriate environment variables in the run-time container, you would have to read `VCAP_SERVICES` again in a `.profile.d`script. It also seems like the `_preprocess_commands` function is not being run in the run-time container, but the staging container. 

Also if you could add unit specs and an integration test for connecting to AppDynamics, that would be great.

**Comment by sclevine** [comment]
Closing in favor of #227.

**Pull request closed without merging**
