### PR TITLE
AppDynamics Service

### PR DESCRIPTION
**Pull request by nkatre**
added .idea to gitignore

added appdynamics svc

Update downloads.py

Update extension.py

Update extension.py

Update manifest.yml

Update extension.py

Update downloads.py

Update manifest.yml

Update extension.py

added appdynamcis test file

Update test_appdynamics.py

appdynamics test file

appdynamics test case

### CODE REVIEW

**Comment by sesmith177** [comment]
Hello @nkatre,

Can you please rebase this PR against the `develop` branch?

**Comment by nkatre** [comment]
@sesmith177 Changed the PR against the develop branch

**Comment by RochesterinNYC** [comment]
@nkatre could you please fix this PR so that there is no merge commit? I'm referring to this merge commit: https://github.com/cloudfoundry/php-buildpack/pull/124/commits/de63a0c2e94956226d250826752d74cb677d0f94

**Comment by sesmith177** [comment]
@nkatre Have you had a chance to update the PR to remove the merge commit de63a0c?

**Comment by nkatre** [comment]
I will work on this this week.

**Comment by nkatre** [comment]
Closing this PR
Continuing here, https://github.com/cloudfoundry/php-buildpack/pull/175

**Pull request closed without merging**
