### PR TITLE
AppDynamics PHP Agent Support

### PR DESCRIPTION
**Pull request by kyle-lt**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:  This change adds support for using the AppDynamics PHP APM agent.

* An explanation of the use cases your change solves: Enables performance monitoring using the AppDynamics platform.

* [X] I have viewed signed and have submitted the Contributor License Agreement

* [X] I have made this pull request to the `develop` branch

* [X] I have added an integration test

### CODE REVIEW

**Comment by kyle-lt** [comment]
Closing in order to reopen after publicizing my org membership.

**Comment by kyle-lt** [comment]
Reopening after publicizing my org membership.

**Comment by nkatre** [comment]
Can we get this PR merged, its been here for a while

**Comment by nkatre** [comment]
@kyle-lt Let me know if there are any concerns to merge the PR

**Comment by kyle-lt** [comment]
Hi @nkatre, I don't have any concerns as of right now.

**Comment by sclevine** [comment]
Thanks @nkatre and @kyle-lt. Prioritizing this now.

**Comment by kyle-lt** [comment]
Thanks @sclevine, when can we expect the merge?

**Comment by nkatre** [comment]
@sclevine, would be better to get this part of next release.

**Comment by dgodd** [comment]
@nkatre @kyle-lt I am about to merge this. However could I ask for a way to have some form of account so that we can start doing some form of full integration test ; eg. Check an API to confirm that data has in fact been received by appdynamics. We would like to have more certainty that everything works for customers

**Comment by kyle-lt** [comment]
@dgodd, you can go grab a 2-week trial here: https://www.appdynamics.com/free-trial/.  This will give you a SaaS AppD Controller for 2 weeks.

**Comment by nkatre** [comment]
@dgodd: we have customers using the a fork of the buildpack with the appdynamics changes to monitor their php applications.

**Comment by sclevine** [comment]
@kyle-lt @nkatre We need a permanent way to run these integration tests in our pipeline. We'd like confirmation from you that you can provide us with a permanent account for testing. Otherwise, we won't have a way to test the feature with future versions of your agent.

**Comment by kyle-lt** [comment]
@sclevine @dgodd @nkatre  I'll work with our partner team to figure this out.  In the meantime, pls merge and feel free to use the trial to test.

**Comment by sclevine** [comment]
Thanks @kyle-lt, will do!

**Comment by kyle-lt** [comment]
Hi @sclevine @dgodd Just checking in before the weekend.  Is there an ETA for the merge?

**Pull request merged**
