### PR TITLE
Integrate Dynatrace into CF PHP-Buildpack

### PR DESCRIPTION
**Pull request by dtpest**
**Dynatrace PHP-Buildpack Integration**

Dynatrace already provides Buildpacks for other programming languages like Java.
Now we also add support to the PHP-Buildpack.

Integration test is available and the approach was discussed with Dave Goddard in the Slack channel.

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

### CODE REVIEW

**Comment by sclevine** [comment]
Looks great! We'll review and merge when you have the CLA submitted.

**Comment by dtpest** [comment]
@sclevine We've already submitted the updated CLA a few weeks ago.
Should we submit it again?

**Comment by sclevine** [comment]
What Github username or organization name did you send with the CLA?

**Comment by dtpest** [comment]
Github Username: dtpest
Mail: peter.studener@dynatrace.com
Organization: Dynatrace

**Comment by sclevine** [comment]
All good now. Prioritized for merge.

**Comment by dtpest** [comment]
Thank you!

**Pull request merged**
