### PR TITLE
fixing httpd-logging link

### PR DESCRIPTION
**Pull request by hochm**

### CODE REVIEW

**Comment by hochm** [comment]
We've signed a Corporate CLA (Swisscom), pls add my usr there.

**Comment by hairmare** [comment]
Hi @hochm 

You need to be in the [swisscom orga](https://github.com/swisscom) on github and mark you membership as public so @cfdreddbot can confirm your CLA.

**Comment by hochm** [comment]
@hairmare  done

**Comment by jvshahid** [comment]
Merged into develop 4245d0ad83c8ad4f1cd889c483665fbcfc9fa30b

**Comment by jvshahid** [comment]
Thanks @hochm for submitting this pr. The pr is merged into the develop branch and will be merged into master soon. Just FYI, you should open new pull requests using `develop` as the base branch. This will make it easier to merge the pr from github UI.

**Pull request closed without merging**
