### PR TITLE
Composer build defaulting to webdir

### PR DESCRIPTION
**Pull request by ArthurHlt**
By default, composer app will install dependencies inside the `webdir` (as it work locally).
You can change to let's the buildpack manage composer installation by putting this `"MANAGED_COMPOSER": "true"` inside your `.bp-config/options.json`.

See discussion here: [https://github.com/cloudfoundry/php-buildpack/issues/65](https://github.com/cloudfoundry/php-buildpack/issues/65)

### CODE REVIEW

**Comment by dmikusa-pivotal** [comment]
Appreciate the PR, not sure I'm happy with the way it works though.  I think this is something that doesn't need a config option.  Instead I think the build pack should just detect the particular use-case this is meant to address and do what it needs to do.

Ex:

If app has not set WEBDIR in .bp-config/options.json &&
   app does not contain the default WEBDIR (i.e. an `htdocs` directory): # this is the current logic
  - create htdocs and move all files there
  - add flag NO_WEBDIR_SET # we just need to flag this some how, so that the Composer extension knows

If app is using Composer && NO_WEBDIR_SET:
  - change directory where Composer is run from BUILD_DIR to BUILD_DIR/WEBDIR

**Comment by ArthurHlt** [comment]
Thanks for the code review, it must be suitable now.

**Comment by dmikusa-pivotal** [comment]
I hate to be picky here, but there are a lot of odd formatting issues which look like whitespace differences that make reading the PR kind of difficult.  What type of tool are you using to edit?  Can you make sure it's set to use four spaces and not tabs and also not auto reformat or break up lines? 

On a slightly different note, but also making this PR hard to read, is that it seems to include some changes which have already been committed like [this](https://github.com/ArthurHlt/php-buildpack/commit/d60f66e15acc439afc2731f152867a16443d736e).  Could you clean this up?  I think it's going to make for a weird merge history.

Lastly, as the @cfdreddbot said, you need a signed CLA before we can merge anything.  See the instructions above.

**Comment by ArthurHlt** [comment]
I use Intellij and it already use 4 spaces when I code in python but well yeah i use auto reformat.
should i close this PR and send an other one cleaned?

About the signed CLA, I'm from Orange and we already appear as contributors (see in the list: [http://cloudfoundry.org/about/index.html](http://cloudfoundry.org/about/index.html) ). Could you fiox this?

**Comment by dmikusa-pivotal** [comment]
It would probably be easier to start with a fresh pull request.  We can see the changes easier and the gitbot will validate your corp as being OK.

I did add a couple comments to the commit link you sent.  Just a couple minor things.  Let me know if you have any questions about those.

**Comment by flavorjones** [comment]
Hi @ArthurH!

To fix the CLA bot message, a few things need to have gone right:

1. Orange needs to have registered its Github Org with the Foundation (who adds it to the bot config). I've confirmed that the github org `Orange-OpenSource-Cf` is on the whitelist.
2. You need to "publicize" your membership in this org, so that the bot can confirm that you're a member. This is currently not true; to the public Github API it looks like you're not a member of this organization.

Instructions for publicizing your membership here: https://help.github.com/articles/publicizing-or-concealing-organization-membership/

**Comment by ArthurHlt** [comment]
@dmikusa-pivotal Really thanks for the code review, I'm not a skilled python developer so that's good you tell me where are bad points. I comment too on your note i prefer did right now before cleaning all the mess.

And @flavorjones thanks for your tips so I did the second I should appear now

**Comment by ArthurHlt** [comment]
I close cause i will break everything to restart from a fresh fork.

**Pull request closed without merging**
