### PR TITLE
Fixed markdown issues in README, fixed general typoes  [issue 108]

### PR DESCRIPTION
**Pull request by krook**
There was a missing end to the code block in at the end of the README. I also rephrased a few sentences and showed that this buildpack also works on Bluemix. I also standardized on "Cloud Foundry" (with a space) and "buildpack" (without a space) in the rest of the docs.

### CODE REVIEW

**Comment by flavorjones** [comment]
Related to #108

**Comment by flavorjones** [comment]
@krook I'll likely have to ask you to resubmit without mentioning specific corporate products, but let me eyeball this changeset and let you know of any other necessary changes?

**Comment by krook** [comment]
@flavorjones Sounds good! The reason I added Bluemix was that the existing docs already mentioned Pivotal Web Services. I wanted it to be pretty clear that this buildpack runs on those public cloud providers, as well as the user's own self hosted instance of Cloud Foundry. I'm happy to make any changes you'd like.

**Comment by krook** [comment]
@flavorjones Any suggested updates?

**Comment by krook** [comment]
Closing, as this is superseded by PR #119

**Pull request closed without merging**
