### PR TITLE
Rephrase PaaS to OneAgent

### PR DESCRIPTION
**Pull request by DTMad**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
We rephrased 'PaaS agent' to 'OneAgent' in our logs and method names.

* An explanation of the use cases your change solves
-

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [ ] I have added an integration test

### CODE REVIEW

**Comment by dfreilich** [comment]
@DTMad Thanks for the PR! We'll look at this and prioritize it soon.

**Comment by DTMad** [comment]
Hey @dfreilich !
Is there anything we can help you with or do you need more information? If so don't hesitate to contact me - Thanks

**Comment by Zanadar** [comment]
@dmikusa-pivotal Can you take a look or we can pair on merging this?

**Comment by arthfl** [comment]
Any estimate on when this will get merged?

**Comment by dfreilich** [comment]
Hey @DTMad @arthfl , thanks for checking in! I just merged it in 409a792ab065cd16fc47bc62f415ee1fae55fedb, and it should be available in our next release.

**Comment by arthfl** [comment]
Thanks :-)

**Pull request closed without merging**
